[package]
name = "rusttasks"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
actix-session = "0.5"

dotenv = "0.15"
env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
