version: "3"

services:

  web:
    build: .
    volumes:
      - ./static:/usr/local/bin/static
    ports:
      - "3030:3030"

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "rusttasks"
      POSTGRES_USER: "rust"
      POSTGRES_PASSWORD: "1111"
    volumes:
       - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"